### ISSUE TITLE
Output expectation

### ISSUE THREAD

**Issue by sinakiaei** [tarcadius/LDAR_Sim#41]
It would be great if there were some output samples in the repository.
To clarify, I'm referring to what users should anticipate seeing after running the code in each step or example.
For instance, within the sensitivity folder, OGI and MGL folders were generated after the first run of LDAR-Sim. Both directories are empty in my situation. So, I'm not sure if this is what I should expect or if I missed something important in these two directories. If both folders are expected to be empty, it's probably best not to create them.

Please disregard this issue if the comment is invalid.

**Comment by tarcadius** [comment]
Hi Sina - thanks for the suggestion. There must be another issue, because LDAR-Sim doesn't create empty folders. Please check out V2, you might have more luck. Best, Thomas
https://github.com/LDAR-Sim/LDAR_Sim
